name: deployment-workflow
on:
  push:
    branches:
      -main
job:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: cache dep
        uses: actions/cache@v3
        with:
          path: ~./npm
          key: dep-${{hashFiles(**/package-lock.json)}}
      - name: get dep
        run: npm ci
      - name: run lint
        run: npm run lint
      - name: run test
        run: npm run test
      - name: make build
        run: npm run build
      - name: build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist
      
      